version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
    volumes:
      - ".mongo:/data/db"